### ISSUE TITLE
Add Traffic

### ISSUE THREAD

**Issue by josuelmm** [Raruto/leaflet-google#1]
Hi, is possible add Layer of Traffic to the map?

**Comment by Raruto** [comment]
A reference to the google maps object is saved inside the leaflet class.

https://github.com/Raruto/leaflet-google/blob/3356eabd9e6d2414509d652c1900dccef9ce6ed6/leaflet-google.js#L151

So you can try doing such a thing:

```js

var map = new L.Map( ... );
var ggl = new L.Google('ROADMAP');

ggl.addTo(map);

var trafficLayer = new google.maps.TrafficLayer();
trafficLayer.setMap(ggl._google);


```

**Comment by josuelmm** [comment]
Ok thanks you.
