### ISSUE TITLE
removing leaflet attribution causes a problem

### ISSUE THREAD

**Issue by slachtar** [Raruto/leaflet-google#2]
Creating a map with:

```js
attributionControl: false
```
causes an error in line [73](https://github.com/Raruto/leaflet-google/blob/3356eabd9e6d2414509d652c1900dccef9ce6ed6/leaflet-google.js#L73) and [92](https://github.com/Raruto/leaflet-google/blob/3356eabd9e6d2414509d652c1900dccef9ce6ed6/leaflet-google.js#L92).

A fix could be, testing the presence of "leaflet-control-attribution" first:

```js
var elem = map._controlCorners["bottomright"].querySelector(".leaflet-control-attribution");
if(elem) elem.style.display = "none";
```

**Comment by Raruto** [comment]
Thanks for the report, now it should be okay.
